name: Release and deploy Todo

on:
  push:
    branches:
    - "v[0-9]+.[0-9]+"

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#NORUN')"
    steps:
    - name: my branch
      run: echo "current branch - ${{ github.ref_name }}"
    - name: Checkout the branch
      uses: actions/checkout@v3
      with:
       ref: ${{ github.ref_name }}
    - name: increase release version
      uses: aurestic/incrementarl-create-release@master
      with:
        flag_branch: true
        message: Bump version
        prev_tag: 'PZ'
        update_odoo_module_version: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: installing railway
      run: npm i -g @railway/cli

    - name: Hello
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.PAINGZAY }}
    - name: Notify Slack
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA55 CI/CD Assignment Submission",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Name:\nPaing Zay"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "Metriculation:\nA0265083A"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Email:\npyne469@gmail.com"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "Repository:\nhttps://github.com/PaingZay/goapplication"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Deployment:\nhttps://loved-soda-production.up.railway.app"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<https://loved-soda-production.up.railway.app/|Open Application>"
                }
              }
            ]
          }
  
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.DIO_BRANDO }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
